version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    environment:
      HUSKY: '0'
    steps:
      - setup_remote_docker:
          version: 20.10.2
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: release
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            npm run semantic-release

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
