version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: test
          command: |
            npm run test
      - run:
          name: docker-build
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
            docker build -t overtheairbrew/tilt-bridge .
      - run:
          name: release
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            npm run semantic-release || true

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
