version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:16'
    environment:
      HUSKY: '0'
      DOCKER_BUILDKIT: 1
      BUILDX_PLATFORMS: linux/arm/v7,linux/arm64/v8,linux/amd64
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: install-dockerx
          command: |
            BUILDX_BINARY_URL="https://github.com/docker/buildx/releases/download/v0.6.3/buildx-v0.6.3.linux-amd64"

            curl --output docker-buildx \
              --silent --show-error --location --fail --retry 3 \
              "$BUILDX_BINARY_URL"

            mkdir -p ~/.docker/cli-plugins

            mv docker-buildx ~/.docker/cli-plugins/
            chmod a+x ~/.docker/cli-plugins/docker-buildx

            docker buildx install
            docker run --rm --privileged tonistiigi/binfmt:latest --install "$BUILDX_PLATFORMS"
      - run:
          name: install
          command: npm ci
      - run:
          name: build
          command: npm run build
      - run:
          name: docker-build
          command: |
            # docker build -t overtheairbrew/tilt-bridge .

            docker buildx build -o type=docker \
              --platform $BUILDX_PLATFORMS \
              --tag overtheairbrew/tilt-bridge .

            docker images
      - run:
          name: release
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
            npm run semantic-release || true

workflows:
  version: 2
  build_release:
    jobs:
      - build:
          context: OVERTHEAIR_HOMEBREW
